### ISSUE TITLE
TOOLS-504 support alternate methods of password passing to tools

### ISSUE THREAD

**Issue by timkuijsten** [mongodb/mongo-tools#12]
In order to fully utilize the new reading from stdin and writing to stdout of the tools, support for a local config file that contains database credentials is really needed.

Currently I find myself constantly appending --authenticationDatabase admin -u myname -p < ~/.fileWithPassword to every commandline tool which makes the cli experience of mongodb really cumbersome and renders reading other data from stdin impossible. An option would be to specify the password on the command line, but this is bad practice from a security point of view (leaves traces in .bash_history and/or ps etc.).

It would be a great improvement in usability and security if passwords and other config data could be read from a config file in the user homedir, in a way like mysql supports ~/.my.cnf for this.

Also see https://jira.mongodb.org/browse/SERVER-5897

**Comment by mpobrien** [comment]
Thanks for the suggestion @timkuijsten, we are working on addressing this very soon - see https://jira.mongodb.org/browse/TOOLS-504. Not 100% sure what the implementation will be yet, but the config file approach seems like a good option to me.

**Comment by billybanfield** [comment]
The central issue here, a security concern with the way passwords are passed to the tools, has largely been addressed by [TOOLS-504](https://jira.mongodb.org/browse/TOOLS-504). I'm going to therefore close for now.
