### ISSUE TITLE
Doesn't build on 32-bit Linux

### ISSUE THREAD

**Issue by felixonmars** [mongodb/mongo-tools#13]
I am getting the following error when building mongo-tools for 32-bit Linux (i686):

```
# github.com/spacemonkeygo/openssl
vendor/src/github.com/spacemonkeygo/openssl/ctx.go:546: constant 2147486719 overflows Options
```

Any hints?

**Comment by hydrapolic** [comment]
I can confirm the same problem on 32bit Linux.

At Gentoo, we have a bug report about it:
https://bugs.gentoo.org/show_bug.cgi?id=544346

We tested with go 1.4.1/1.4.2, openssl 1.0.1/1.0.2, all fail.

**Comment by hydrapolic** [comment]
@felixonmars, can you please test this:

--- vendor/src/github.com/spacemonkeygo/openssl/ctx.go.orig	2015-03-09 23:14:45.000000000 +0100
+++ vendor/src/github.com/spacemonkeygo/openssl/ctx.go	2015-03-26 13:41:39.730177906 +0100
@@ -533,7 +533,7 @@
 	return nil
 }
 
-type Options int
+type Options int64
 
 const (
 	// NoCompression is only valid if you are using OpenSSL 1.0.1 or newer

**Comment by felixonmars** [comment]
@hydrapolic The patch works fine for me, thanks a lot!

**Comment by ultrabug** [comment]
FYI: this was added on the Gentoo ebuild to fix the issue for now.

**Comment by felixonmars** [comment]
I am adding it to the Arch PKGBUILD, too :)

**Comment by mpobrien** [comment]
Fixed in https://github.com/mongodb/mongo-tools/commit/086956dd3d1d2d40204022e495bc0f319aef60b7
