### ISSUE TITLE
UTF-8 BOM is not ignored

### ISSUE THREAD

**Issue by emilh91** [mongodb/mongo-tools#31]
This issue was fixed a while back when the MongoDB tools were written in C++: https://github.com/mongodb/mongo/commit/2e6c1584c09c5326faf22e927814d15485fbfd2a

However, it made its way back in since the tools were moved to their own repository. 
Now, when running mongoimport with a CSV file with the BOM, it is part of the first key of every document. In short, the BOM should be ignored.

**Comment by emilh91** [comment]
FYI - updated to version 3.0.5 and the issue still exists.

**Comment by mpobrien** [comment]
Thanks for the report @emilh91 - opened a JIRA ticket to track this here: https://jira.mongodb.org/browse/TOOLS-879
Will see about getting a fix in soon.

**Comment by armond1978** [comment]
Is there any ETA for the fix?

**Comment by lucasem** [comment]
Fixed in 59a747a.

You could build the tools yourself or wait for the next release to take advantage of the fix.
