### ISSUE TITLE
Add option for mongorestore to ignore some collections

### ISSUE THREAD

**Issue by soleo** [mongodb/mongo-tools#41]
It would be great if mongorestore could ignore some collections with an argument in command line.

It could be ``--ignoreCol="Col1,Col2" ``

**Comment by mpobrien** [comment]
Thanks for this idea @soleo, I've also filed it in JIRA here: https://jira.mongodb.org/browse/TOOLS-976

**Comment by soleo** [comment]
Thanks, @mpobrien. I was planning to implement this, but it looks like you guys are working on it.

**Comment by mpobrien** [comment]
@soleo actually, nobody's picked up this ticket yet, so we'd be happy to take a pull request from you for this if you're still interested in working on it!

**Comment by soleo** [comment]
@mpobrien , okay. I'm going to pick this up. A little change for this issue. Since mongodump support two flags related to this feature in version 3.0.0
```
--excludeCollection array of strings
--excludeCollectionsWithPrefix array of strings
```
I'm going to make it consistent with that, supporting both excludeCollection and excludeCollectionsWithPrefix. and excludeCollectionsWithPrefix and excludeCollection cannot appear with --collection. Sounds good?

**Comment by mpobrien** [comment]
@soleo Yup, that sounds good. Thanks for taking this one!

**Comment by soleo** [comment]
This is merged, so I think it's okay to close this issue now. @mpobrien

**Comment by pzelnip** [comment]
Given that 3.3 isn't out yet, is there a workaround for this for those who need the ability to exclude a collection right now?

**Comment by soleo** [comment]
@pzelnip you could probably just compile the branch from https://github.com/soleo/mongo-tools/tree/TOOLS-976 and use it. I think the same feature has been merged into master branch as well, so if you compile your version of binary from master branch, it would work, too.
