### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by renjithvrs755** [mongodb/mongo-tools#44]
i got this error, while running this "http://www.sitepoint.com/building-simple-blog-app-mongodb-php/"

i really need your help. i am a new comer to coding

Fatal error: Uncaught exception 'MongoConnectionException' with message 'Failed to connect to: 127.0.0.1:27017: SASL Authentication failed on database 'blog': Authentication failed.' in C:\xampp\htdocs\s\db.php:28 Stack trace: #0 C:\xampp\htdocs\s\db.php(28): MongoClient->__construct('mongodb://127.0...', Array) #1 C:\xampp\htdocs\s\db.php(19): Blog\DB\DB->connect(Array) #2 C:\xampp\htdocs\s\app.php(10): Blog\DB\DB->__construct(Array) #3 C:\xampp\htdocs\s\index.php(5): require('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\s\db.php on line 28

**Comment by gabrielrussell** [comment]
This sort of question is best directed at a mongodb user group, like https://groups.google.com/d/forum/mongodb-user , or http://stackoverflow.com/questions/tagged/mongodb . This here is for people to work on building mongodb itself.
