### ISSUE TITLE
mongodump is not working on ipv6-only hosts

### ISSUE THREAD

**Issue by Qwiz** [mongodb/mongo-tools#47]
Hi.

I'm trying to set up mongo cluster on hosts without ipv4 address. Mongod works great, but mongodump don't - it can't connect to running instance. 

> $ mongodump --username user --password password --authenticationDatabase authdb --host fqdn --port 27017 --db db --out /path/to/backup/backup-$(date +%s)
> Failed: error connecting to db server: no reachable servers

There is no option `--ipv6`, mentioned in [docs](https://docs.mongodb.org/manual/reference/program/mongodump/). It seems to be removed in commit `cc26004ac9b08b2a3decfee972b73b8965dd0681` without any comment, so I have no idea why did it happen.

Please, fix it.
Thanks.

**Comment by gabrielrussell** [comment]
Qwiz, did you build mongodump from source? If it's from source, what commit did you build? If not, then what exact version did you download?

**Comment by gabrielrussell** [comment]
Also, can you try to run mongodump replacing the fqdn with the ip address, and see if that functions any better?

**Comment by gabrielrussell** [comment]
Lastly, can you enclose the ip address in [] on the command line. Something like:
```
mongodump  --host '[::1]'
```

**Comment by tp7** [comment]
Version 3.0.7. 
Replacing the fqdn with the ip address indeed works, only when it's enclosed with []. So mongodump can connect to an ipv6-only host, it just cannot resolve it by fqdn.

**Comment by gabrielrussell** [comment]
This is correct. This should be nearly the same in 3.2 when it comes out. Full support for ipv6 in the tools is forthcoming.

The reason that the tools don't currently support resolving ipv6 fqdn's is that this feature is not currently supported by mgo, the go mongodb driver. The feature is under development currently. Soon after the feature is finished in the driver, it will show up in the 3.2 tools, and probably in the 3.0 tools.

**Comment by gabrielrussell** [comment]
@Qwiz the ipv6 code has been improved quite a bit since you opened this up in November 2015. Can you see if the problems you initially encountered are still present in using a 3.4 version of the tools?
