### ISSUE TITLE
mongorestore stopped and showed insertion error: EOF

### ISSUE THREAD

**Issue by soleo** [mongodb/mongo-tools#48]
I was trying to restore a mongo dump to my local machine, but "Insertion error" come up.

The command I used is 
```
mongorestore  --db dev --drop --objcheck --maintainInsertionOrder ${MONGODBFILEPATH}
```
Error Dump
```
2015-11-24T17:44:12.908-0600	Failed: restore error: dev.XXX: error restoring from mongodb/Backup/XXX.bson: insertion error: EOF
```

Any idea why it happened?

```
# mongorestore --version
mongorestore version: 3.0.7
git version: not-built-with-ldflags
```

**Comment by soleo** [comment]
Is it a memory issue?
Ref http://dba.stackexchange.com/questions/108517/mongorestore-failure-error-writing-file-var-lib-mongodb

**Comment by soleo** [comment]
More info about the issue.

The error is genterated by bson_stream.go line 126-138

```
var n int
	n, err = io.ReadAtLeast(bs.Stream, into[4:], int(bsonSize-4)) 
	if err != nil {
		if err != io.EOF {
			//bs.err = err
			bs.err = fmt.Errorf("BSONSource::LoadNext BufferRead:%v Expected:%v", n, int(bsonSize-4))
			return nil
		}
		// this case means we hit EOF but read a partial document,
		// so there's a broken doc in the stream. Treat this as error.
		bs.err = fmt.Errorf("invalid bson: %v", err)
		return nil
	}
```
I tried to get the debugging info, it turns out the it read less than BSONSize
```
2015-11-25T17:55:17.905-0600	Failed: dev.ABC: error restoring from ABC.bson: reading bson input: BSONSource::LoadNext BufferRead:196 Expected:462
``

However, the BSON file is not corrupted or invalid. What could be the cause of the issue. The collection size is about 700MB

**Comment by mpobrien** [comment]
@soleo a few questions to help debug - are you able to bsondump the entire file? (try bsondump filename.bson > output.json) This would double-check that the bson is valid or not. That particular error indicates that the size of the bson header doesn't agree with the number of bytes available in the stream.

**Comment by soleo** [comment]
@mpobrien ,

the dump file is corrupted because of "no space on device" error when dumping. 
```
2015-11-25T04:33:01.277-0600	Failed: error writing to file: write dump/ABC.bson: no space left on device
```
I just saw that in our server. 

And ``bsondump`` shows ``2015-11-30T11:07:36.956-0600	unexpected EOF``.

The question is "Why would mongodump still saving the bson file if it is corrupted?" Does it make more sense to discard the bson file if it is invalid or encountered error?

**Comment by mpobrien** [comment]
@soleo If I understand this correctly, mongodump did the correct behavior - it dumped as much of the collection as possible, but then stopped and displayed an error as soon as the filesystem prevented it from writing any further. It's not possible for mongodump to determine a priori if writing the BSON will succeed or not. Discarding the bson file in that case seems be a bit extreme, since it would result in destroying potentially large amounts of data that could still be used for at least a partial restore. It would also be pretty easy to wrap mongodump in a script that checks its exit code and deletes any dump output if the exit code is non-zero, if that's your desired behavior.

Otherwise, I think it's up to the user to either verify that the dump command completed successfully before trying to use its output with mongorestore (or validate it prior to restoring it).

**Comment by soleo** [comment]
@mpobrien thanks. I think we can close this issue now. I'm pretty sure the bson file was invalid because of running out disk memory.

**Comment by soleo** [comment]
@mpobrien , I have another collection errored out when restoring. This time, the output for
``` 
bsondump collection.bson >  output.json
```
is simply the total count of the collection.
```
2015-12-01T13:29:33.818-0600	32857 objects found 
```

Looks like the issue still persists.

**Comment by soleo** [comment]
The issue happened only to mongorestore version: 3.0.7, but it's working for the builds from master branch. Is it possible that the issue has been fixed but not reported?

**Comment by mpobrien** [comment]
@soleo actually yes, you're correct - though this is a different root cause than the invalid BSON issue that you were running into initially. It looks like an occurrence of this issue: https://jira.mongodb.org/browse/TOOLS-939. This was fixed for 3.0.8 which will be released within the next few days, but is available in master now as you have noticed.

**Comment by soleo** [comment]
@mpobrien Thanks. I want to use collection exclusion in my envrionment, so building with my fork would make more sense.

**Comment by soleo** [comment]
for anyone who is interested which part of code was fixing the issue, this should be it https://github.com/mongodb/mongo-tools/commit/b4338162d8799ce948d5e20d97acf80d6f1a4cf1

**Comment by JohnnyY8** [comment]
@soleo Hi!
I am meeting the same error like following:
![qq 20160715112259](https://cloud.githubusercontent.com/assets/12611573/16862694/8eb8eafe-4a7e-11e6-8a1d-992b1a060912.png)
Could you please tell me what is your solution ?

**Comment by zachjs** [comment]
@JohnnyY8 `EOF` usually indicates that the server has crashed. Can you check your server logs?

**Comment by JohnnyY8** [comment]
@zachjs Hi!
I have not check logs, but I can connect to mongos. Does that mean the server not crashed ?
And when I run "show dbs" command, there are some exception I do not know why.
![image](https://cloud.githubusercontent.com/assets/12611573/16863187/c8804f62-4a82-11e6-874d-95085a776658.png)
Does that mean shard3 is crashed or something?
Thanks a lot!

**Comment by zachjs** [comment]
@JohnnyY8 Yes, it appears that the shard did crash or is otherwise down. Restarting that shard should resolve your issue. However, info from the shard's logs could help us determine what caused it to fail in the first place.

**Comment by JohnnyY8** [comment]
@zachjs OK, thank you.
I have dumped the all data. So I want to clean the data and config files, then restart mongodb.

**Comment by zachjs** [comment]
@JohnnyY8 Has your issue been resolved then? Do you have any further questions?

**Comment by JohnnyY8** [comment]
@zachjs I tryed to fix the shard3 and waiting for the result of restoring.
That looks good. Thank you so much!

**Comment by pzelnip** [comment]
I am having this issue as well while restoring a collection into a Mongo Atlas cluster.  The mongodump command did exit with 0 error code (the shell script that ran the job ```&&```'s the commands together and I see no evidence of failure), and looking at the logged output of mongodump I see:

```
Tue Aug 30 08:02:15.933         foobar.e_events to backup-dump/foobar/e_events.bson
... many lines of Collection File Writing Progress: .....
Tue Aug 30 08:17:43.104                 Collection File Writing Progress: 4199400/4286466       97%     (objects)
Tue Aug 30 08:17:44.473                  4286473 objects
Tue Aug 30 08:17:44.473         Metadata for foobar.e_events to backup-dump/foobar/e_events.metadata.json
```
Followed by the output of the rest of the backup.

Note that mongodump was a Mongo 2.4 instance, and I'm importing this dump into a Mongo 3.2 instance using the 3.2 mongorestore, does that matter?

**Comment by pzelnip** [comment]
FWIW, I think the problem was memory related: I ended up killing the Atlas cluster and trying again with a much larger instance (went from an M10 with 2GB of RAM to a M40 with 16GB, and the machine I was running the restore from went from 8GB to 16GB).  Seemed to solve the problem.

**Comment by xerosanyam** [comment]
It was a memory related issue. My server had just 1GB ram and no swap space.
I solved it by adding swap space using following instructions: http://askubuntu.com/questions/566745/allocate-swap-after-ubuntu-14-04-lts-installation
