### ISSUE TITLE
set_gopath.sh failure

### ISSUE THREAD

**Issue by nodeleaf** [mongodb/mongo-tools#50]
Platform: go version go1.5.1 ob linux/amd64 (Ubuntu 15.10)

Steps:
1 - sudo apt-get install golang-go
2 - sudo git clone https://github.com/mongodb/mongo-tools.git
3 - sudo ./set_gopath.sh
4 -  echo $GOPATH <strong> -> returns an empty line</strong>
5 - sudo go build -o ../../bin/mongoimport mongoimport/main/mongoimport.go

`mongoimport/main/mongoimport.go:6:2: cannot find package "github.com/mongodb/mongo-tools/common/db" in any of:`
`	/usr/lib/go/src/github.com/mongodb/mongo-tools/common/db (from $GOROOT)
	($GOPATH not set)`
`mongoimport/main/mongoimport.go:7:2: cannot find package "github.com/mongodb/mongo-tools/common/log" in any of:`
`	/usr/lib/go/src/github.com/mongodb/mongo-tools/common/log (from $GOROOT)
	($GOPATH not set)`
`mongoimport/main/mongoimport.go:8:2: cannot find package "github.com/mongodb/mongo-tools/common/options" in any of:`
`	/usr/lib/go/src/github.com/mongodb/mongo-tools/common/options (from $GOROOT)
	($GOPATH not set)`
`mongoimport/main/mongoimport.go:9:2: cannot find package "github.com/mongodb/mongo-tools/common/signals" in any of:`
`	/usr/lib/go/src/github.com/mongodb/mongo-tools/common/signals (from $GOROOT)
	($GOPATH not set)`
`mongoimport/main/mongoimport.go:10:2: cannot find package "github.com/mongodb/mongo-tools/common/util" in any of:`
`	/usr/lib/go/src/github.com/mongodb/mongo-tools/common/util (from $GOROOT)
	($GOPATH not set)`
`mongoimport/main/mongoimport.go:11:2: cannot find package "github.com/mongodb/mongo-tools/mongoimport" in any of:`
	`/usr/lib/go/src/github.com/mongodb/mongo-tools/mongoimport (from $GOROOT)
	($GOPATH not set)`

**Comment by persisted** [comment]
Try running this instead:
source ./set_gopath.sh
or
. ./set_gopath.sh

**Comment by mpobrien** [comment]
As noted above, you should be able to use . ./set_gopath.sh - this is required because it needs to modify GOPATH in the existing shell session, not spawn a new one.
