### ISSUE TITLE
3.0 Ubuntu packages signature is broken.

### ISSUE THREAD

**Issue by breser** [mongodb/mongo-tools#51]
I have the 7F0CEB10 key installed as per the Ubuntu instructions and am getting this:

```
15-Dec-2015 10:24:48 	W: GPG error: http://repo.mongodb.org trusty/mongodb-org/3.0 Release: The following signatures were invalid: BADSIG 9ECBEC467F0CEB10 Richard Kreuter <richard@10gen.com>
15-Dec-2015 10:24:49 	WARNING: The following packages cannot be authenticated!
15-Dec-2015 10:24:49 	  mongodb-org-tools
```
Note that this is a completely automated installation (including setting up the key) and has been working for months.

**Comment by breser** [comment]
Ok maybe I was too quick to open this.  Running this by hand and re-running the automation succeeds.  Maybe I just had a corrupted download.

**Comment by mpobrien** [comment]
@breser Closing this for now but please let us know if there's any other issues. Thanks!
