### ISSUE TITLE
mongoexport occasionally returns 0 records when there is data

### ISSUE THREAD

**Issue by elephantjim** [mongodb/mongo-tools#54]
We have a project that uses a nightly task to export some data from MongoLab to a cluster for use in Hive.  We use mongoexport to fetch the data and write lines of JSON.  As our project ramped up we began to notice that every once in a while, mongoexport would return 0 records (even though we know for certain that data is there).

One issue is to figure out why mongoexport sees no data when there is.  We think it might be due a slow response time from the server, and mongoexport gets confused and drops the connection.  See https://github.com/christkv/mongodb-core/issues/66 for example.

Another issue (that is perhaps easier to get at) is that mongoexport gives no indication that something is wrong.  It emits no warning to stderr, cheerfully reports that 0 records got exported, and returns exit code 0 (no error).  An example command is:
```
mongoexport --host myReplicaSetName/myHost1:myPort1,myHost2:myPort2 --username myUserName --password myPassword --db myDbName --collection myCollectionName --type json --slaveOk
```
and its output is:
```
connected to: myReplicaSetName/myHost1:myPort1,myHost2:myPort2
exported 0 records
```
and the exit code is 0.

Any ideas what the cause might be?  Or what the fix is?

**Comment by elephantjim** [comment]
Oops.  Almost forgot to mention: we're running version 3.0.8.

**Comment by mpobrien** [comment]
@elephantjim can you try running with more verbose debugging output by adding -vvvv to the arguments? it may show some more details that will be useful.
Also - any log snippets from the server-side from the time when the mongoexport was run?

**Comment by elephantjim** [comment]
Ok, will do.  However, we just upgraded our hardware to reduce write wait times.  It may be a while before we see the error again.

**Comment by elephantjim** [comment]
Say, I tried the options for verbose output from mongoexport, but nothing additional is written.  I've tried `--verbose` and `-v` up to `-vvvvv`.  Should I be seeing any additional output?

**Comment by elephantjim** [comment]
I got a chance to take a look at the mongod.log from around the time of one of the incidents.  I think I may have found the culprit, but I could use some feedback.

Our workflow goes as follows.  S'pose we want to export collection X.  We rename collection X to X_2016_01_01.  We create a new collection named "X" with whatever indices the old collection had.  We run mongoexport on X_2016_01_01.  We drop X_2016_01_01.  Note we use `--slaveOk` as an option to mongoexport.

I'm wondering if the problem is replication lag between the primary and secondary.  That is, if we export X_2016_01_01 from the secondary before the secondary has renamed the collection from X to X_2016_01_01, might it think there are no records to export?

During a successful export, I see records like this on the primary:
```
2015-12-30T21:07:35.112-0800 [conn1136270] build index on: winbox-live.queue_info properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "winbox-live.queue_info" }
2015-12-30T21:07:37.021-0800 [conn1136284] CMD: drop winbox-live.queue_info_2015_12_30
```
and records like this on the secondary:
```
2015-12-30T21:07:35.116-0800 [repl writer worker 3] build index on: winbox-live.queue_info properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "winbox-live.queue_info" }
2015-12-30T21:07:35.325-0800 [conn43631] getmore winbox-live.queue_info_2015_12_30 cursorid:301736743641 ntoreturn:0 keyUpdates:0 numYields:206 locks(micros) r:66763 nreturned:8117 reslen:2232196 141ms
2015-12-30T21:07:37.531-0800 [repl writer worker 4] CMD: drop winbox-live.queue_info_2015_12_30
```

A failed export looks very similar, but the "getmore" on the secondary is missing.  On the primary:
```
2015-12-30T21:07:37.053-0800 [conn1136287] build index on: winbox-live.worker_info properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "winbox-live.worker_info" }
2015-12-30T21:07:37.892-0800 [conn1136291] CMD: drop winbox-live.worker_info_2015_12_30
```
and on the secondary:
```
2015-12-30T21:07:37.538-0800 [repl writer worker 4] build index on: winbox-live.worker_info properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "winbox-live.worker_info" }
2015-12-30T21:07:38.120-0800 [repl writer worker 4] CMD: drop winbox-live.worker_info_2015_12_30
```

Do you think inserting a one second pause between the rename and the export might solve the problem?  At the start of the successful export, there seems to be only a few millisecond lag between the primary and secondary, but at the start of the failed export there's about 500 milliseconds of lag.

**Comment by mpobrien** [comment]
@elephantjim Your assessment about the replication lag as the cause seems correct. A one second delay might mitigate the issue, but wouldn't eliminate the root cause and if replication lag ever crept above your sleep delay it might end up just happening again.
Can you omit the --slaveOk option to mongoexport? Then you wouldn't need to add any pauses, as reading from the primary will guarantee that you're seeing the most up-to-date view of the data.

**Comment by elephantjim** [comment]
Ok, thanks!

Can I turn my bug-report-that-isn't into a feature request?  The node mongo driver has a "strict" option.  If set, trying to open a collection that doesn't exist throws an error.  See https://github.com/christkv/node-mongodb-native#strict-mode

In my case, I'd much rather receive an error from mongoexport that tells me the collection doesn't exist rather than getting no error and "successfully" returning 0 records.  It would distinguish that case from a collection that really does have no records.  Is that feature possible?

**Comment by mpobrien** [comment]
@elephantjim sure - can you file a ticket [here](https://jira.mongodb.org/browse/TOOLS) for the feature request? Then we can close out this ticket, and look at that separately.

**Comment by elephantjim** [comment]
Thanks!  I filed https://jira.mongodb.org/browse/TOOLS-1034
