### ISSUE TITLE
Mongodump fails silently on version mismatch

### ISSUE THREAD

**Issue by deg** [mongodb/mongo-tools#55]
Running v2.4 of mongodump on a remote 3.2 mongodb results in an apparently successful connection, but no data backed up and no error message.  Even with -vvvvv, no error or warning message.

I hit this situation without realizing it. (Details irrelevant, but FWIW: a docker script updated the mongdb version I was using, but I hosted in an existing AWS instance that was grabbing backups. I didn't realize to update its version of mongodump too).

I can easily imagine this biting many other configurations too. It would be good if mongodump issued an error when it sees a db version that it can't read.

**Comment by mpobrien** [comment]
@deg The 2.4 version of mongodump is quite old and no longer being maintained, it was originally part of the github.com/mongodb/mongo repo - as of the 3.0 release the mongo tools were moved to this repo,  and should work fine against any mongo server version. There's no fix we can provide here other than to recommend using a newer version of mongodump.
