### ISSUE TITLE
Gopass changed a method

### ISSUE THREAD

**Issue by SommerEngineering** [mongodb/mongo-tools#56]
The library gopass has changed the return value of a method:
https://github.com/howeyc/gopass/blob/master/pass.go

`getPasswd()` returns now the data and an error. Thus, the mongo-tools does not compile any longer, caused by `common/password/pass_util.go`'s `GetPass()`.

**Comment by SommerEngineering** [comment]
I have created a pull request with the fix.

**Comment by gabrielrussell** [comment]
Since we vender Gopass, this will get fixed when we revender it.

**Comment by gabocic** [comment]
Hi gabrielrussell,

Do you have an estimation of when this issue will get fixed?

thanks in advance

**Comment by gabrielrussell** [comment]
Gabocic,

Are you currently having trouble building a version of the tools? I don't know of any actual problem currently with building any released version of the tools.

**Comment by gabocic** [comment]
gabrielrussel,

Still seeing the same problem:

(myserver:~/gopath) go get github.com/mongodb/mongo-tools/common/password
# github.com/mongodb/mongo-tools/common/password
src/github.com/mongodb/mongo-tools/common/password/pass_util.go:20: multiple-value gopass.GetPasswd() in single-value context

**Comment by gabrielrussell** [comment]
I can't really tell what you're trying to do there. If you want to build the tools, you should follow the instructions here: https://github.com/mongodb/mongo-tools#setup, and here: https://github.com/mongodb/mongo-tools#building-tools

**Comment by ys-roposo** [comment]
gabriellrussell,
  [multiple-value gopass.GetPasswd() in single-value context when installing #36](https://github.com/ParsePlatform/flashback/issues/36)

  building flashback fails, as mentioned by tredman.

**Comment by gabrielrussell** [comment]
Applications often have dependencies. Generally not all versions of the software is compatible with all versions of dependencies. They way that we solve this in our project is to vendor in the dependencies that we know our application is compatible with.

The application you're trying to build needs a way to manage its dependencies on versions of its dependencies.

If you have trouble building _our_ application, using the provided instructions then feel free to let me know.

**Comment by gabrielrussell** [comment]
mongo-tools ships with a version of gopass that its compatible with. We build a GOPATH with a script in the root of the project called set_gopath.sh, that lets us build against the included dependencies. While the application that you're tying to build may not be able to run set_gopath.sh directly, you it may be able to incorporate the knowledge withing and build against the correct vendored dependencies.

**Comment by ys-roposo** [comment]
Thanks, resoved using SommerEngineering [pull](https://github.com/mongodb/mongo-tools/pull/57/commits) request.
