### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by mwhudson** [mongodb/mongo-tools#67]
If you run the tests by running `. set_gopath.sh; go test ./common/log ./common/archive ./common/bsonutil ./common/db ./common/intents ./common/json ./common/options ./common/progress ./common/text ./common/util ./mongodump ./mongoexport ./mongofiles ./mongoimport ./mongooplog ./mongorestore ./mongostat` in a checkout, the following tests fail:

```
(master)mwhudson@aeglos:mongo-tools$ grep -E '^(FAIL)\s' test-out.txt
FAIL	_/opt/opensource/mongo-tools/common/archive	0.076s
FAIL	_/opt/opensource/mongo-tools/common/intents [build failed]
```

If you run go get github.com/mongodb/mongo-tools and fiddle so that the version of github.com/spacemonkeygo/openssl is the one from vendor (apparently the one at tip is no longer compatible?), and run `go test github.com/mongodb/mongo-tools/...`, two more tests fail:

```
mwhudson@aeglos:src$ grep -E '^FAIL\s' test-out.txt
FAIL	github.com/mongodb/mongo-tools/common/log [setup failed]
FAIL	github.com/mongodb/mongo-tools/bsondump	0.064s
FAIL	github.com/mongodb/mongo-tools/common/archive	0.093s
FAIL	github.com/mongodb/mongo-tools/common/intents [build failed]
```

**Comment by mpobrien** [comment]
Hi @mwhudson - thanks for the heads up! This has been fixed - see https://jira.mongodb.org/browse/TOOLS-1167 for details.
