### ISSUE TITLE
Missing 3.0.11 release

### ISSUE THREAD

**Issue by ultrabug** [mongodb/mongo-tools#69]
Hi,

I'm packaging mongodb for Gentoo Linux and since mongodb-3.0.11 got released, we're lacking a mongo-tools-3.0.11 too please ?

See : https://bugs.gentoo.org/show_bug.cgi?id=580796

Cheers

**Comment by ultrabug** [comment]
Same with 3.0.12

**Comment by gabrielrussell** [comment]
Previously tagging the tools project was a prerequisite of our release process. This was actually error prone. So, we changed how our release process works, and having the tags in the repo is not part of it any longer.

We'll automate the generation of these tags in the near future. 

I've just manually created the r3.0.11 and r3.0.12 tags. Reopen if you need need anything more.

Thank you,
Gabriel
