### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by Lujeni** [mongodb/mongo-tools#72]
Hi,

There is a [jira issue ](https://jira.mongodb.org/browse/TOOLS-1168 ) about the project tagging (missing 3.2.6 and 3.2.7). Sorry for the duplicata

Can you manually create the tag please?

Thanks

**Comment by Lujeni** [comment]
Hi,

Any news pls?

**Comment by zachjs** [comment]
Thank you for pointing out this issue. I manually created tags for [r3.2.6](https://github.com/mongodb/mongo-tools/releases/tag/r3.2.6) and [r3.2.7](https://github.com/mongodb/mongo-tools/releases/tag/r3.2.7). Please let me know if I can be of further assistance.
