### ISSUE TITLE
Mention mongoreplay in README.md

### ISSUE THREAD

**Issue by ryandesign** [mongodb/mongo-tools#79]
The [README.md](https://github.com/mongodb/mongo-tools/blob/master/README.md) file does not mention the new [mongoreplay](https://docs.mongodb.com/manual/release-notes/3.4/#mongoreplay) tool added in 3.4.0.

**Comment by gabrielrussell** [comment]
I've created https://jira.mongodb.org/browse/TOOLS-1577 to track this work.
