### ISSUE TITLE
Release tag for 3.4.1

### ISSUE THREAD

**Issue by jakesjews** [mongodb/mongo-tools#83]
Can we get a tag for 3.4.1 so that https://github.com/Homebrew/homebrew-core/pull/8127 can be merged?

**Comment by ultrabug** [comment]
Same problem here for Gentoo Linux packaging.
https://bugs.gentoo.org/show_bug.cgi?id=602434

This problem is not new and have been reported fixed but it looks like something is still missing guys.
https://jira.mongodb.org/browse/TOOLS-1168?filter=-2

**Comment by ehershey** [comment]
Done.
