### ISSUE TITLE
FDTC file viewer

### ISSUE THREAD

**Issue by TingKwadraat** [mongodb/mongo-tools#89]
Hello Everybody,

MongoDB produces DTFC files with diagnostic information.
Are there tools to read these files? 
Especially in cases of issues this might be helpful.

I have been looking around on internet, but no result.

Tnx in advance for your help!

**Comment by billybanfield** [comment]
Hey @TingKwadraat!
Thanks for reaching out through the mongo-tools project. Unfortunately we don't distribute a tool for examining the FTDC data created by mongo
