### ISSUE TITLE
build fails on arm64 due to missing dup2

### ISSUE THREAD

**Issue by ncopa** [mongodb/mongo-tools#95]
When building mongo-tools-3.4.4 on arm64 I get the following error:

````
# github.com/spacemonkeygo/spacelog
vendor/src/github.com/spacemonkeygo/spacelog/capture_other.go:26: undefined: syscall.Dup2
vendor/src/github.com/spacemonkeygo/spacelog/capture_other.go:30: undefined: syscall.Dup2
````

Looks like it has been fixed in upstream: https://github.com/spacemonkeygo/spacelog/commit/f936fb050dc6b5fe4a96b485a6f069e8bdc59aeb

**Comment by billybanfield** [comment]
hey @ncopa Thanks for filing this issue! We've revendored our version of spacelog to include the dup2 fix. 

https://jira.mongodb.org/browse/TOOLS-1109
